datacarpentry/OpenRefine-ecology-lesson

01-working-with-openrefine.md
The lesson objectives have been updated to be more specific than the previous ones. I've based these objectives on the updated version suggested in pull request https://github.com/datacarpentry/OpenRefine-ecology-lesson/pull/17.
=> Improve learning objectives of lesson

00-getting-started.md
Revised learning objectives to align with assessment goals.
=> Updated learning objectives

00-getting-started.md
My first pull request using GitHub, for instructor training checkout. Hoping I haven't botched it. Just fixed some typos and clarified a little bit of language.
=> Updating 00-getting-started.md

01-working-with-openrefine.md
This asks the learner to facet a different column (year) and interpret the results by observing the number of unique years and sorting by counts for each year.
=> Added a challenge for faceting

_episodes/01-working-with-openrefine.md
Addresses https://github.com/datacarpentry/OpenRefine-ecology-lesson/issues/61 and more listed below.
=> fixes to wording and typos for 01-working-with

_episodes/00-getting-started.md, _episodes/02-filter-exclude-sort.md, _episodes/03-numbers.md, _episodes/04-scripts.md, _episodes/05-save-export.md, _episodes/07-resources.md, _extras/guide.md
Remove duplicate learning objectives from all episodes. Remove inconsistent learning objectives from instructor notes.
=> Fix learning objectives

_episodes/01-working-with-openrefine.md, _episodes/02-filter-exclude-sort.md, _episodes/03-numbers.md, _episodes/04-scripts.md, _episodes/05-save-export.md, _episodes/07-resources.md, _extras/guide.md
Update time estimates for all episodes.
=> Time estimates

CITATION
Addresses https://github.com/datacarpentry/OpenRefine-ecology-lesson/issues/53
=> add citation

_episodes/01-working-with-openrefine.md
Addresses https://github.com/datacarpentry/OpenRefine-ecology-lesson/issues/56 and https://github.com/datacarpentry/OpenRefine-ecology-lesson/issues/70
=> update data location to figshare

_episodes/02-filter-exclude-sort.md, _episodes/03-numbers.md, _episodes/04-scripts.md, _episodes/05-save-export.md, _episodes/06-resources.md
Addresses https://github.com/datacarpentry/OpenRefine-ecology-lesson/issues/77
=> Remove prev next

_includes/navbar.html
Fixes https://github.com/datacarpentry/OpenRefine-ecology-lesson/issues/52
=> update link to code of conduct

_episodes/02-filter-exclude-sort.md
- reformat one of the challenges
- species --> specie
Fixes https://github.com/datacarpentry/OpenRefine-ecology-lesson/issues/74
=> typos and formatting

_extras/guide.md
Closes https://github.com/datacarpentry/OpenRefine-ecology-lesson/issues/58
=> reorganize guide to follow template

_episodes/01-working-with-openrefine.md, _episodes/02-filter-exclude-sort.md, _episodes/03-numbers.md, _episodes/04-scripts.md, _episodes/05-save-export.md
Fixes https://github.com/datacarpentry/OpenRefine-ecology-lesson/issues/67
=> Add code blocks

_extras/figures.md
Fixes https://github.com/datacarpentry/OpenRefine-ecology-lesson/issues/55
=> removed figures.md file

_episodes/00-getting-started.md, _episodes/01-working-with-openrefine.md, _episodes/02-filter-exclude-sort.md, _episodes/03-numbers.md, _episodes/04-scripts.md, _episodes/05-save-export.md, _episodes/06-resources.md
Convert questions in overview to actual questions.
Fixes https://github.com/datacarpentry/OpenRefine-ecology-lesson/issues/120
=> Questions as questions

_episodes/01-working-with-openrefine.md, _episodes/02-filter-exclude-sort.md, _episodes/03-numbers.md, _episodes/04-scripts.md, _episodes/05-save-export.md
This PR addresses a few typos and replaces idioms with more non-geographically specific language.
=> Minor wording

CONDUCT.md, CONTRIBUTING.md, NEWS.md
=> added NEWS.md and updated admin files

_episodes/03-numbers.md
Fixes https://github.com/datacarpentry/OpenRefine-ecology-lesson/issues/112
=> Explain data types

_episodes/04-scripts.md
Added some motivating text for scripts and an additional follow-along demo. Also defined the JSON acronym and added more explanation of how to save the file as plain text.
=> Explain scripts more

_extras/guide.md
The link to the data in the instructor notes was to the dropbox folder. I've updated to the FigShare link.
=> Update data link

XX-services.md
Clarify that services module is not part of current lesson.
=> Update and rename 06-services.md to XX-services.md

_extras/guide.md
Fixes https://github.com/datacarpentry/OpenRefine-ecology-lesson/issues/96
=> add solution to bug

_episodes/01-working-with-openrefine.md, _episodes/02-filter-exclude-sort.md, _episodes/03-numbers.md
Add solutions for some exercises. Part of lesson release.
=> Add solutions

_episodes/00-getting-started.md
was previously resolving to http://www.datacarpentry.org/OpenRefine-ecology-lesson/00-getting-started/
---
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process …
=> fixed link to openrefine.org

_extras/guide.md, setup.md
The original link was pointing to the messy spreadsheets data
=> Fixed link to data set

_extras/guide.md
=> adding info on common problem

_episodes/01-working-with-openrefine.md
complements https://github.com/datacarpentry/OpenRefine-ecology-lesson/pull/170
=> move extra info on faceting to callout box

_episodes/00-getting-started.md
Added clearer language that OpenRefine operations on data can be undone, added direct link to intro videos, cleaned up language regarding Google Plus community language and OpenRefine libraries sharing language, to be more specific.
=> Modified language to be clearer and added direct links to material

_episodes/04-scripts.md
I have added more info about reproducible science + reference to articles using the principles in actual research
=> Script episode edited (instructor checkout)

_episodes/01-working-with-openrefine.md
Reduce confusing word choices in Working with OpenRefine module.
Closes #157.
=> Fix typo and phrasing

_episodes/05-save-export.md
=> provide instructions on opening `tar.gz` files for Windows users

setup.md
Open Refine released the final 3.1 version at the end of November 2018 so I have changed it here
---
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or …
=> Changed OpenRefine 2.8 to 3.1

index.md
---
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact Kate Hertweck …
=> Small typo fix

index.md
as per issue #231 https://github.com/datacarpentry/OpenRefine-ecology-lesson/issues/231
Please delete the text below before submitting your contribution.
=> fix grammar: insure to ensure

_episodes/01-working-with-openrefine.md
grammar and occasional word choice for clarity
=> minor_grammatical_edits

_episodes/00-getting-started.md
---
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact Kate Hertweck …
=> typo - closing parenthesis

_episodes/02-filter-exclude-sort.md
Line previously read " A good distinction is that faceting gives you an overview description of all of the data that 
is currently" now reads " A good distinction is that faceting gives you an overview description of all the data that 
is currently" after removal of second 'of' on line 46. Grammatical error fixed, more concise language implemented.
* Data Carpentries Instructor Checkout Contribution *
---
Please keep in mind that lesson …
=> Fixed Grammatical Error; Line 46, double "of"

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Replacing me with Carpentries Team as the point of contact
=> updating contact person

_episodes/00-getting-started.md
I changed the language around the browsers so that it no longer required learners to change their default browser but still made it clear which browsers were best (as proposed by @maneesha in issue #233). I also made the software download link live.
=> Updated setup instructions

_extras/guide.md
Changed reference to google_refine.exe to openrefine.exe
=> Updated filename

_episodes/05-save-export.md
Fixed wording and reorganized the instructions for clarity.
Please delete the text below before submitting your contribution.
=> drdn-edits-to-exporting-lesson

_episodes/01-working-with-openrefine.md
Added clarification to use the spacebar in step 3 of the split exercise as suggested by @valkcano26 at  #https://github.com/datacarpentry/OpenRefine-ecology-lesson/issues/163
=> Clarification on split

_episodes/05-save-export.md
This menu option was changed in recent OpenRefine (tested on 3.4.1).
=> Update export option name

_episodes/00-getting-started.md
I fixed one missing end parentheses, added the live link to a URL, updated language and punctuation, and separated an important tip out of the list of motivations for using OpenRefine.
=> Copy-edit of introduction

_episodes/01-working-with-openrefine.md
Removes section on trim and makes note of behavior when opening a project in 3.4+.
Closes issue #245.
=> Removing trim since it is a default in 3.4

_episodes/00-getting-started.md, _episodes/01-working-with-openrefine.md, _episodes/02-filter-exclude-sort.md, _episodes/05-save-export.md, _episodes/06-resources.md, _extras/guide.md, setup.md
Tested the text and instructions so that it works with OpenRefine 3.4.1.
=> Openrefine 3.4.1

_episodes02-filter-exclude-sort.md
I suggest a few edits to this page to make work flow easier on a new learner.  
1) I enhanced the solutions to the Filtering exercise by separating out and expanding on the multiple suggested solutions, plus removing the suggested solution "you could split the scientificName column into species and genus before filtering".  This is because I tried to follow through with this suggestion and quickly found that, in order to split scientificName column into species and genus *before filtering*, it would require the student to learn how to split the column properly.  If they do split the column, they may be confused by top entries which did not split because they require further data clean up.  I believe if this suggestion is to remain, further changes will need to be made to walk the student …
=> Enhance text and remove confusing "solution"

_episodes/01-working-with-openrefine.md
Not sure how but seems a commit brought this section again.
This PR will remove that section.
=> Removing trim per #245

_episodes/01-working-with-openrefine.md, _episodes/02-filter-exclude-sort.md, _episodes/03-numbers.md
Suggested solution for Issue #237
=> changed 'Facet's to lowercase

_episodes/06-resources.md
Removes very old and outdated resources as well as imports links from https://librarycarpentry.org/lc-open-refine/setup.html
=> Cleanup of resources for issue #259

_episodes/00-getting-started.md
=> Updating text, #268

_episodes/01-working-with-openrefine.md, _extras/guide.md
OpenRefine has moved docs from github wiki to docs.openrefine.org
Please delete the text below before submitting your contribution.
=> Fix broken links to openrefine wiki

_episodes/01-getting-started.md
Now on discourse.org - in last couple of weeks. Google group is deprecated
Please delete the text below before submitting your contribution.
---
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer …
=> Open Refine has moved from its google group

.zenodo.json
Adds @troub1 to `.zenodo.json` since #280 was merged
=> add author from most recent changes

_episodes/03-exploring-data.md
This will help render the lesson correctly during the transition (see https://fishtree-attempt.github.io/OpenRefine-ecology-lesson/03-exploring-data.html#callout1)
=> add missing block quote character

episodes/04-transforming-data.md
Step 6 of this section says there are seven options after clustering, but there are actually ten. The screenshot shows this, and so will OpenRefine if you are following along with the lesson.
=> Fix Data Clustering section

episodes/02-importing-data.md, episodes/04-transforming-data.md, episodes/05-filter-exclude-sort.md, episodes/06-reconciliation.md
_If this pull request addresses an open issue on the repository, please add 'Closes #NN' below, where NN is the issue number._
_Please briefly summarise the changes made in the pull request, and the reason(s) for making these changes._
Fix a few typos.
_If any relevant discussions have taken place elsewhere, please provide links to these._
<details>
For more guidance on how to contribute changes to a Carpentries project, please review [the Contributing Guide](CONTRIBUTING.md) and [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html).
Please keep in mind that lesson Maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate …
=> Fix some typos
